app:
  env: local
  name: app-server-local
debug: true
frontEnd:
  baseUrl: https://app.com
  dashboard:
    baseUrl: https://app.com
http:
  port: 3000
globalCache:
  host: 127.0.0.1
  port: 6379
  db: 0
throttling:
  limit: 10
  ttl: 60
database:
  url: postgres://postgres:postgres@127.0.0.1:5432/nester
  schema: public
authentication:
  passwordRegEx: ^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$
  allowRegisterNewUser: true
  allowUnverifiedSignin: true
  registerUserOnSendOtp: true
  allowImpersonation: true
  token:
    jwtSecret: replace_me
    accessTokenExpiration: PT1H
    refreshTokenExpiration: P100D
  providers: 
    google:
      clientId: replace_me
      clientSecret: replace_me
storage:
  type: minio
  maxFileSize: 30_000_000
  minio:
    privateBucket: private
    publicBucket: public
    accessKeyId: w3pTLtcQEKiaCnCxFrLn
    secretAccessKey: WOcezNiM9WjrQrnDxlpta6uAgrlpUGZFm7ep19Tl
    storageEndpoint: http://localhost:9009
mailer:
  provider: local
  sender: no-reply@app.com
  host: replace_me
  auth:
    user: replace_me
    pass: replace_me
swagger:
  enabled: true
  apiUrl: http://localhost:3000
sentry:
  enabled: false
  dsn: replace_me
  tracesSampleRate: 1.0
  profilesSampleRate: 1.0
captcha:
  enabled: false
  provider: recaptcha
  recaptcha:
    verifyUrl: https://www.google.com/recaptcha/api/siteverify
    secret: replace_me
logger:
  console:
    enabled: true
    level: debug
  fluent:
    enabled: false
    host: localhost
    port: 24224
    timeout: 3.0
    requireAckResponse: false 
rabbit:
  uri: 'amqp://localhost:5672'
defaultUser:
  email: amir.msc90@gmail.com
  mobile: +989189757114
  password: 123456789
smsSender:
  provider: kavenegar
  kavenegar:
    apiKey: 725337335236466D6A6569344A4A4E717A5132614E42766C644F794F47473769706E31787239596454416B3D